version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "bootstrap"
        versions: ["5.2.x"]
      - dependency-name: "postcss"
    groups:
      frontend:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      backend:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/clotributor-apiserver"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "node"
        versions: ["19-alpine3.19", "20-alpine3.19", "21-alpine3.19", "22-alpine3.19", "22-alpine3.20", "23-alpine3.21"]

  - package-ecosystem: "docker"
    directory: "/clotributor-registrar"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/clotributor-tracker"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/database/migrations"
    schedule:
      interval: "monthly"

