{{- if .Capabilities.APIVersions.Has "batch/v1/CronJob" }}
apiVersion: batch/v1
{{- else }}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: {{ include "chart.resourceNamePrefix" . }}tracker
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
        {{- with .Values.tracker.cronjob.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          restartPolicy: Never
          initContainers:
            - {{- include "chart.checkDbIsReadyInitContainer" . | nindent 14 }}
          containers:
            - name: tracker
              image: {{ .Values.tracker.cronjob.image.repository }}:{{ .Values.imageTag | default (printf "v%s" .Chart.AppVersion) }}
              imagePullPolicy: {{ .Values.pullPolicy }}
              {{- with .Values.tracker.cronjob.containerSecurityContext }}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              resources:
                {{- toYaml .Values.tracker.cronjob.resources | nindent 16 }}
              volumeMounts:
                - name: tracker-config
                  mountPath: {{ .Values.configDir | quote }}
                  readOnly: true
              command: ['clotributor-tracker', '-c', '{{ .Values.configDir }}/tracker.yaml']
          volumes:
            - name: tracker-config
              secret:
                secretName: {{ include "chart.resourceNamePrefix" . }}tracker-config
