name: Build images

on:
  push:
    branches:
      - main

env:
  OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
  OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
  OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
  OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
  OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}

jobs:
  build-dbmigrator-image:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Login to OCI Registry
        id: login-ocir
        uses: oracle-actions/login-ocir@v1.3.0
        with:
          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}
      - name: Get clotributor dbmigrator OCIR repository
        id: get-ocir-repository-dbmigrator
        uses: oracle-actions/get-ocir-repository@v1.3.0
        with:
          name: clotributor/dbmigrator
          compartment: ${{ secrets.OCI_COMPARTMENT_OCID }}
      - name: Build and push dbmigrator image
        env:
          OCIR_REPOSITORY: ${{ steps.get-ocir-repository-dbmigrator.outputs.repo_path }}
        run: |
          docker build \
            -f database/migrations/Dockerfile \
            -t $OCIR_REPOSITORY:$GITHUB_SHA \
            .
          docker push $OCIR_REPOSITORY:$GITHUB_SHA

  build-apiserver-image:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Login to OCI Registry
        id: login-ocir
        uses: oracle-actions/login-ocir@v1.3.0
        with:
          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}
      - name: Get clotributor apiserver OCIR repository
        id: get-ocir-repository-apiserver
        uses: oracle-actions/get-ocir-repository@v1.3.0
        with:
          name: clotributor/apiserver
          compartment: ${{ secrets.OCI_COMPARTMENT_OCID }}
      - name: Build and push apiserver image
        env:
          OCIR_REPOSITORY: ${{ steps.get-ocir-repository-apiserver.outputs.repo_path }}
        run: |
          docker build \
            -f clotributor-apiserver/Dockerfile \
            -t $OCIR_REPOSITORY:$GITHUB_SHA \
            .
          docker push $OCIR_REPOSITORY:$GITHUB_SHA

  build-registrar-image:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Login to OCI Registry
        id: login-ocir
        uses: oracle-actions/login-ocir@v1.3.0
        with:
          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}
      - name: Get clotributor registrar OCIR repository
        id: get-ocir-repository-registrar
        uses: oracle-actions/get-ocir-repository@v1.3.0
        with:
          name: clotributor/registrar
          compartment: ${{ secrets.OCI_COMPARTMENT_OCID }}
      - name: Build and push registrar image
        env:
          OCIR_REPOSITORY: ${{ steps.get-ocir-repository-registrar.outputs.repo_path }}
        run: |
          docker build \
            -f clotributor-registrar/Dockerfile \
            -t $OCIR_REPOSITORY:$GITHUB_SHA \
            .
          docker push $OCIR_REPOSITORY:$GITHUB_SHA

  build-tracker-image:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Login to OCI Registry
        id: login-ocir
        uses: oracle-actions/login-ocir@v1.3.0
        with:
          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}
      - name: Get clotributor tracker OCIR repository
        id: get-ocir-repository-tracker
        uses: oracle-actions/get-ocir-repository@v1.3.0
        with:
          name: clotributor/tracker
          compartment: ${{ secrets.OCI_COMPARTMENT_OCID }}
      - name: Build and push tracker image
        env:
          OCIR_REPOSITORY: ${{ steps.get-ocir-repository-tracker.outputs.repo_path }}
        run: |
          docker build \
            -f clotributor-tracker/Dockerfile \
            -t $OCIR_REPOSITORY:$GITHUB_SHA \
            .
          docker push $OCIR_REPOSITORY:$GITHUB_SHA
